DROP INDEX IF EXISTS idx_channels_inbox;

ALTER TABLE IF EXISTS channels
DROP COLUMN IF EXISTS inbox_id;

ALTER TABLE IF EXISTS sessions
DROP COLUMN IF EXISTS inbox_id;

ALTER TABLE IF EXISTS agents
DROP COLUMN IF EXISTS inbox_ids;

DROP TABLE IF EXISTS inboxes;
